import type { Metadata } from 'next'
import './globals.css'
import { poppins } from './font'
import Header from '@/components/Partials/Header'

export const metadata: Metadata = {
    title: 'Next TicTacToe',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <Header />
                <main>{children}</main>
            </body>
        </html>
    )
}
